### ISSUE TITLE
please add workdir to the image

### ISSUE THREAD

**Issue by archchen** [daxingplay/docker-overture#1]

**Comment by archchen** [comment]
FROM alpine

ENV VERSION v1.4-rc1

RUN set -xe && \
    mkdir /config && \
    apk add --no-cache unzip curl && \
    curl -fsSLO --compressed "https://github.com/shawn1m/overture/releases/download/${VERSION}/overt
ure-linux-amd64.zip" && \
    unzip -o "overture-linux-amd64.zip" -d /srv && \
    rm -rf "overture-linux-amd64.zip" && \
    apk del unzip curl

COPY config.json /config/
VOLUME [ "/config" ]
WORKDIR /srv
CMD [ "/srv/overture-linux-amd64", "-c", "/config/config.json" ]

**Comment by daxingplay** [comment]
Thanks for reporting this issue. `WORKDIR` added in 548b96199946ec8b34a605b9631754978c937ed0 and pushed a new image tag for [v1.4-rc1](https://hub.docker.com/r/daxingplay/docker-overture/tags/)
